apiVersion: install.tetrate.io/v1alpha1
kind: Tier1Gateway
metadata:
  name: tier1-gw
  namespace: tier1
spec:
  connectionDrainDuration: 5s
  kubeSpec:
    deployment:
      hpaSpec:
        maxReplicas: 10
        metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 75
              type: Utilization
          type: Resource
        minReplicas: 1
      strategy:
        rollingUpdate:
        type: RollingUpdate
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ports:
      - name: tls-istio-mtls
        port: 15443
        targetPort: 15443
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
      - name: http-t1-healthcheck
        port: 9443
        targetPort: 9443
      type: LoadBalancer
  revision: default
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Gateway
metadata:
  name: tier1-bookinfo-gw
  annotations:
    tsb.tetrate.io/organization: qa-stack-test
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: bookinfo-ws
    tsb.tetrate.io/gatewayGroup: bookinfo-gg
spec:
  workloadSelector:
    namespace: tier1
    labels:
      app: tier1-gw
  http:
    - name: productpage
      port: 80
      hostname: "bookinfo.tetrate.io"
      routing:
        rules:
          - route:
              clusterDestination:
                clusters: []
