apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: qa-stack-test
  tenant: platform-tests
  name: bookinfo-ws-4
spec:
  namespaceSelector:
    names:
      - '*/bookinfo-4'
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: qa-stack-test
  tenant: platform-tests
  workspace: bookinfo-ws-4
  name: bookinfo-gw-4
spec:
  namespaceSelector:
    names:
      - '*/bookinfo-4'
  configMode: BRIDGED
